#!/bin/bash

# SFTP upload script
SERVER="72.60.209.172"
USER="root"
PROJECT_DIR="/root/kip"

echo "🚀 Starting SFTP upload session..."
echo "Commands to run in SFTP:"
echo ""
echo "sftp $USER@$SERVER"
echo "cd $PROJECT_DIR"
echo "cd core"
echo "put core/views_dashboard.py"
echo "put core/serializer.py" 
echo "put core/utils.py"
echo "cd ../backend"
echo "put backend/settings_production.py"
echo "quit"
echo ""
echo "Or run this single command:"
echo "sftp $USER@$SERVER << 'EOF'"
echo "cd $PROJECT_DIR/core"
echo "put core/views_dashboard.py"
echo "put core/serializer.py"
echo "put core/utils.py"
echo "cd ../backend"
echo "put backend/settings_production.py"
echo "quit"
echo "EOF"
