# Generated by Django 5.2.7 on 2025-10-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_subservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WORKING_HOURS_START', models.IntegerField(default=9, help_text='Start hour (24-hour format)')),
                ('WORKING_HOURS_END', models.IntegerField(default=17, help_text='End hour (24-hour format)')),
                ('DEFAULT_RESERVATION_DURATION_MINUTES', models.IntegerField(default=60, help_text='Duration in minutes')),
                ('OFF_DAYS', models.CharField(blank=True, default='', help_text='Comma-separated days (0=Monday, 6=Sunday)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Settings',
                'verbose_name_plural': 'Booking Settings',
            },
        ),
    ]
