# Generated by Django 5.2.7 on 2025-10-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Offer image', null=True, upload_to='offers/'),
        ),
    ]
