# Generated by Django 5.2.7 on 2025-10-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.URLField(blank=True, help_text='Offer image URL', max_length=500, null=True),
        ),
    ]
